services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    image: immersion-calculator:v2.0
    container_name: immersion_calculator_v2
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - TZ=UTC
    restart: unless-stopped
    networks:
      - calculator-network
    volumes:
      - ./logs:/app/logs
    labels:
      - "com.example.description=Immersion Cooling TCO Calculator"
      - "com.example.version=2.0"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: calculator_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - calculator
    networks:
      - calculator-network
    profiles:
      - production

networks:
  calculator-network:
    driver: bridge

volumes:
  logs:
    driver: local